# Generated by Django 3.2.18 on 2023-09-25 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content_services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='contentdetails',
            name='content_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contentdetails',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contentdetails',
            name='deleted_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contentdetails',
            name='modified_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
