# Generated by Django 3.2.18 on 2023-09-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_services', '0002_auto_20230926_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentdetails',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
