# Generated by Django 3.2.18 on 2023-09-25 18:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('fullname', models.CharField(max_length=256)),
                ('user_role', models.CharField(max_length=256)),
                ('phone', models.IntegerField(max_length=256)),
                ('address', models.CharField(max_length=256, null=True)),
                ('city', models.CharField(max_length=256, null=True)),
                ('state', models.CharField(max_length=256, null=True)),
                ('country', models.CharField(max_length=256, null=True)),
                ('pincode', models.IntegerField(max_length=256)),
                ('is_deleted', models.IntegerField(default=False, max_length=256)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.CreateModel(
            name='ContentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=256, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('body', models.CharField(max_length=256)),
                ('summary', models.CharField(max_length=256)),
                ('document', models.CharField(max_length=256)),
                ('categories', models.CharField(max_length=256)),
                ('delete_by', models.CharField(max_length=256, null=True)),
                ('is_deleted', models.IntegerField(default=False)),
                ('created_datetime', models.DateTimeField(max_length=256, null=True)),
                ('modified_datetime', models.DateTimeField(max_length=256, null=True)),
                ('deleted_datetime', models.DateTimeField(max_length=256, null=True)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userdetails')),
            ],
            options={
                'db_table': 'content_details',
            },
        ),
    ]
